workflows:
  android-workflow:
    name: Haryana GK AAB
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create Android folder
        script: |
          cp lib/main.dart /tmp/my_main.dart
          flutter create . --platforms android --project-name haryana_gk_quiz
          cp /tmp/my_main.dart lib/main.dart
      - name: Build AAB
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - dramandhillon720@gmail.com
