
workflows:
  android-workflow:
    name: Haryana GK Quiz Android
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: 3.35.4
      java: 17
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Fix Android folder and Add Real AdMob ID
        script: |
          rm -rf android
          flutter create . --platforms=android
          flutter pub get
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          perl -i -pe 'BEGIN{undef $/;} s/<application[^>]*>/\0\n    <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-2827494424235072~8673663489"\/>/' $MANIFEST
          echo "Manifest Fixed with Real ID"
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.apk
