workflows:
  android-workflow:
    name: Haryana GK Quiz Android
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: 3.27.1
      java: 17
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Fix Android folder
        script: |
          rm -rf android
          flutter create . --platforms=android
          flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.apk
